Repository irontec/ivoz-ui, pull requests merged in 2022-10, with the labels that each got.

#17 Added isPropertyScalar date & date-time format condition
  src/entities/DefaultEntityBehavior/ListDecorator.tsx
Labels: enhancement

#18 Added throw error in silenceError conditional in api post
  src/store/api.ts
Labels: bug, enhancement

#21 Fixed itemsPerPage variable in List component
  src/components/List/List.tsx
Labels: bug

#22 Multiple bug fixes
  package.json
  src/components/List/Content/ListContentValue.tsx
  src/components/List/Content/Table/ContentTable.tsx
  src/components/List/Content/hook/useParentIden.ts
  src/components/List/Filter/ContentFilterSelector.tsx
  src/components/List/List.tsx
  src/components/List/Pagination.tsx
  src/components/layout/Menu/MenuBlock.styles.tsx
  src/components/layout/Menu/MenuBlock.tsx
  src/services/form/Field/Autocomplete.tsx
  src/services/form/FormFieldFactory.tsx
  src/store/api.ts
  src/store/auth.ts
  src/store/menu.ts
Labels: bug
