Repository irontec/ivoz-ui, pull requests merged in 2024-08, with the labels that each got.

#126 Fixed hygen templates
  demo/bin/generate-cy-subscreen-test
  demo/bin/generate-cy-test
  demo/bin/generate-entity
  library/hygen/templates/entity/new/Entity.ejs.t
  library/hygen/templates/entity/new/Form.ejs.t
  library/package.json
Labels: bug, enhancement

#127 Fixed missing seconds on date-time filters
  library/package.json
  library/src/services/form/Field/TextField/TextField.tsx
Labels: bug

#128 Downloadable file option in column
  library/package.json
  library/src/components/List/Content/ListContentValue.tsx
  library/src/components/List/DownloadFile.styles.tsx
  library/src/components/List/DownloadFile.tsx
  library/src/services/api/ParsedApiSpecInterface.ts
Labels: enhancement
